services:
  dog-backend:
    build:
      context: ./app
    container_name: dog-backend
    env_file:
      - .env_example
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:15
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    container_name: database
    env_file:
      - .env_example
    ports:
      - "5432:5432"
